/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.searchlight.client.models;

import java.util.Objects;
import com.appscode.searchlight.client.models.V1alpha1IncidentNotification;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1IncidentStatus
 */

public class V1alpha1IncidentStatus {
  @SerializedName("lastNotificationType")
  private String lastNotificationType = null;

  @SerializedName("notifications")
  private List<V1alpha1IncidentNotification> notifications = null;

  public V1alpha1IncidentStatus lastNotificationType(String lastNotificationType) {
    this.lastNotificationType = lastNotificationType;
    return this;
  }

   /**
   * Type of last notification, such as problem, acknowledgement, recovery or custom
   * @return lastNotificationType
  **/
  @ApiModelProperty(required = true, value = "Type of last notification, such as problem, acknowledgement, recovery or custom")
  public String getLastNotificationType() {
    return lastNotificationType;
  }

  public void setLastNotificationType(String lastNotificationType) {
    this.lastNotificationType = lastNotificationType;
  }

  public V1alpha1IncidentStatus notifications(List<V1alpha1IncidentNotification> notifications) {
    this.notifications = notifications;
    return this;
  }

  public V1alpha1IncidentStatus addNotificationsItem(V1alpha1IncidentNotification notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<V1alpha1IncidentNotification>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Notifications for the incident, such as problem or acknowledgement.
   * @return notifications
  **/
  @ApiModelProperty(value = "Notifications for the incident, such as problem or acknowledgement.")
  public List<V1alpha1IncidentNotification> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<V1alpha1IncidentNotification> notifications) {
    this.notifications = notifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1IncidentStatus v1alpha1IncidentStatus = (V1alpha1IncidentStatus) o;
    return Objects.equals(this.lastNotificationType, v1alpha1IncidentStatus.lastNotificationType) &&
        Objects.equals(this.notifications, v1alpha1IncidentStatus.notifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastNotificationType, notifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1IncidentStatus {\n");
    
    sb.append("    lastNotificationType: ").append(toIndentedString(lastNotificationType)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

