/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.searchlight.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1Receiver
 */

public class V1alpha1Receiver {
  @SerializedName("notifier")
  private String notifier = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("to")
  private List<String> to = null;

  public V1alpha1Receiver notifier(String notifier) {
    this.notifier = notifier;
    return this;
  }

   /**
   * How this notification will be sent
   * @return notifier
  **/
  @ApiModelProperty(value = "How this notification will be sent")
  public String getNotifier() {
    return notifier;
  }

  public void setNotifier(String notifier) {
    this.notifier = notifier;
  }

  public V1alpha1Receiver state(String state) {
    this.state = state;
    return this;
  }

   /**
   * For which state notification will be sent
   * @return state
  **/
  @ApiModelProperty(value = "For which state notification will be sent")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public V1alpha1Receiver to(List<String> to) {
    this.to = to;
    return this;
  }

  public V1alpha1Receiver addToItem(String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<String>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * To whom notification will be sent
   * @return to
  **/
  @ApiModelProperty(value = "To whom notification will be sent")
  public List<String> getTo() {
    return to;
  }

  public void setTo(List<String> to) {
    this.to = to;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1Receiver v1alpha1Receiver = (V1alpha1Receiver) o;
    return Objects.equals(this.notifier, v1alpha1Receiver.notifier) &&
        Objects.equals(this.state, v1alpha1Receiver.state) &&
        Objects.equals(this.to, v1alpha1Receiver.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notifier, state, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1Receiver {\n");
    
    sb.append("    notifier: ").append(toIndentedString(notifier)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

