/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.searchlight.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * V1alpha1IncidentNotification
 */

public class V1alpha1IncidentNotification {
  @SerializedName("author")
  private String author = null;

  @SerializedName("checkOutput")
  private String checkOutput = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("firstTimestamp")
  private DateTime firstTimestamp = null;

  @SerializedName("lastTimestamp")
  private DateTime lastTimestamp = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("type")
  private String type = null;

  public V1alpha1IncidentNotification author(String author) {
    this.author = author;
    return this;
  }

   /**
   * name of user making comment
   * @return author
  **/
  @ApiModelProperty(value = "name of user making comment")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public V1alpha1IncidentNotification checkOutput(String checkOutput) {
    this.checkOutput = checkOutput;
    return this;
  }

   /**
   * brief output of check command for the incident
   * @return checkOutput
  **/
  @ApiModelProperty(value = "brief output of check command for the incident")
  public String getCheckOutput() {
    return checkOutput;
  }

  public void setCheckOutput(String checkOutput) {
    this.checkOutput = checkOutput;
  }

  public V1alpha1IncidentNotification comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * comment made by user
   * @return comment
  **/
  @ApiModelProperty(value = "comment made by user")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public V1alpha1IncidentNotification firstTimestamp(DateTime firstTimestamp) {
    this.firstTimestamp = firstTimestamp;
    return this;
  }

   /**
   * The time at which this notification was first recorded. (Time of server receipt is in TypeMeta.)
   * @return firstTimestamp
  **/
  @ApiModelProperty(value = "The time at which this notification was first recorded. (Time of server receipt is in TypeMeta.)")
  public DateTime getFirstTimestamp() {
    return firstTimestamp;
  }

  public void setFirstTimestamp(DateTime firstTimestamp) {
    this.firstTimestamp = firstTimestamp;
  }

  public V1alpha1IncidentNotification lastTimestamp(DateTime lastTimestamp) {
    this.lastTimestamp = lastTimestamp;
    return this;
  }

   /**
   * The time at which the most recent occurrence of this notification was recorded.
   * @return lastTimestamp
  **/
  @ApiModelProperty(value = "The time at which the most recent occurrence of this notification was recorded.")
  public DateTime getLastTimestamp() {
    return lastTimestamp;
  }

  public void setLastTimestamp(DateTime lastTimestamp) {
    this.lastTimestamp = lastTimestamp;
  }

  public V1alpha1IncidentNotification state(String state) {
    this.state = state;
    return this;
  }

   /**
   * state of incident, such as Critical, Warning, OK, Unknown
   * @return state
  **/
  @ApiModelProperty(required = true, value = "state of incident, such as Critical, Warning, OK, Unknown")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public V1alpha1IncidentNotification type(String type) {
    this.type = type;
    return this;
  }

   /**
   * incident notification type.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "incident notification type.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1IncidentNotification v1alpha1IncidentNotification = (V1alpha1IncidentNotification) o;
    return Objects.equals(this.author, v1alpha1IncidentNotification.author) &&
        Objects.equals(this.checkOutput, v1alpha1IncidentNotification.checkOutput) &&
        Objects.equals(this.comment, v1alpha1IncidentNotification.comment) &&
        Objects.equals(this.firstTimestamp, v1alpha1IncidentNotification.firstTimestamp) &&
        Objects.equals(this.lastTimestamp, v1alpha1IncidentNotification.lastTimestamp) &&
        Objects.equals(this.state, v1alpha1IncidentNotification.state) &&
        Objects.equals(this.type, v1alpha1IncidentNotification.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, checkOutput, comment, firstTimestamp, lastTimestamp, state, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1IncidentNotification {\n");
    
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    checkOutput: ").append(toIndentedString(checkOutput)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    firstTimestamp: ").append(toIndentedString(firstTimestamp)).append("\n");
    sb.append("    lastTimestamp: ").append(toIndentedString(lastTimestamp)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

