/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.searchlight.client.models;

import java.util.Objects;
import com.appscode.searchlight.client.models.V1alpha1PluginVarField;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1PluginVars
 */

public class V1alpha1PluginVars {
  @SerializedName("fields")
  private Map<String, V1alpha1PluginVarField> fields = new HashMap<String, V1alpha1PluginVarField>();

  @SerializedName("required")
  private List<String> required = null;

  public V1alpha1PluginVars fields(Map<String, V1alpha1PluginVarField> fields) {
    this.fields = fields;
    return this;
  }

  public V1alpha1PluginVars putFieldsItem(String key, V1alpha1PluginVarField fieldsItem) {
    this.fields.put(key, fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(required = true, value = "")
  public Map<String, V1alpha1PluginVarField> getFields() {
    return fields;
  }

  public void setFields(Map<String, V1alpha1PluginVarField> fields) {
    this.fields = fields;
  }

  public V1alpha1PluginVars required(List<String> required) {
    this.required = required;
    return this;
  }

  public V1alpha1PluginVars addRequiredItem(String requiredItem) {
    if (this.required == null) {
      this.required = new ArrayList<String>();
    }
    this.required.add(requiredItem);
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  @ApiModelProperty(value = "")
  public List<String> getRequired() {
    return required;
  }

  public void setRequired(List<String> required) {
    this.required = required;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PluginVars v1alpha1PluginVars = (V1alpha1PluginVars) o;
    return Objects.equals(this.fields, v1alpha1PluginVars.fields) &&
        Objects.equals(this.required, v1alpha1PluginVars.required);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, required);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PluginVars {\n");
    
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

