/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.searchlight.client.models;

import java.util.Objects;
import com.appscode.searchlight.client.models.V1alpha1PluginVars;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1PluginArguments
 */

public class V1alpha1PluginArguments {
  @SerializedName("host")
  private Map<String, String> host = null;

  @SerializedName("vars")
  private V1alpha1PluginVars vars = null;

  public V1alpha1PluginArguments host(Map<String, String> host) {
    this.host = host;
    return this;
  }

  public V1alpha1PluginArguments putHostItem(String key, String hostItem) {
    if (this.host == null) {
      this.host = new HashMap<String, String>();
    }
    this.host.put(key, hostItem);
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getHost() {
    return host;
  }

  public void setHost(Map<String, String> host) {
    this.host = host;
  }

  public V1alpha1PluginArguments vars(V1alpha1PluginVars vars) {
    this.vars = vars;
    return this;
  }

   /**
   * Get vars
   * @return vars
  **/
  @ApiModelProperty(value = "")
  public V1alpha1PluginVars getVars() {
    return vars;
  }

  public void setVars(V1alpha1PluginVars vars) {
    this.vars = vars;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PluginArguments v1alpha1PluginArguments = (V1alpha1PluginArguments) o;
    return Objects.equals(this.host, v1alpha1PluginArguments.host) &&
        Objects.equals(this.vars, v1alpha1PluginArguments.vars);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, vars);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PluginArguments {\n");
    
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    vars: ").append(toIndentedString(vars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

