/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.searchlight.client.apis;

import com.appscode.searchlight.client.ApiException;
import io.kubernetes.client.models.V1APIResourceList;
import io.kubernetes.client.models.V1DeleteOptions;
import io.kubernetes.client.models.V1Status;
import com.appscode.searchlight.client.models.V1alpha1Acknowledgement;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IncidentsMonitoringAppscodeComV1alpha1Api
 */
@Ignore
public class IncidentsMonitoringAppscodeComV1alpha1ApiTest {

    private final IncidentsMonitoringAppscodeComV1alpha1Api api = new IncidentsMonitoringAppscodeComV1alpha1Api();

    
    /**
     * 
     *
     * create an Acknowledgement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespacedAcknowledgementTest() throws ApiException {
        String namespace = null;
        V1alpha1Acknowledgement body = null;
        String pretty = null;
        V1alpha1Acknowledgement response = api.createNamespacedAcknowledgement(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete an Acknowledgement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespacedAcknowledgementTest() throws ApiException {
        String name = null;
        String namespace = null;
        V1DeleteOptions body = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        String pretty = null;
        String propagationPolicy = null;
        V1Status response = api.deleteNamespacedAcknowledgement(name, namespace, body, gracePeriodSeconds, orphanDependents, pretty, propagationPolicy);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIResourcesTest() throws ApiException {
        V1APIResourceList response = api.getAPIResources();

        // TODO: test validations
    }
    
}
